volumes:
  certs:
    external: true

services:
  dyndns:
    build: ./dyndns
    container_name: dyndns
    depends_on: 
      - web

  web:
    image: httpd:latest
    container_name: web
    env_file:
      - .env
    volumes:
      - ./web/htdocs:/usr/local/apache2/htdocs
      - ./web/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./web/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - certs:/etc/letsencrypt
    ports:
      - 8080:80
      - 4433:443

  url-shortener:
    build: 
      context: ./url-shortener
      target: builder
    stop_signal: SIGINT
    container_name: url-shortener
    env_file:
      - .env
    expose:
      - 5000